---
title: "Grad Cafe Analysis "
author: "Ryan Longmuir"
date: "4/16/2020"
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 3
    toc_float: yes
    fig_width: 8
    fig_height: 4 
---

```{r packages & functions , include = F}

# -----------------------------------------------------------------------------
# packages 
# -----------------------------------------------------------------------------

library(tidyverse)
library(reshape2)
library(lubridate)
library(kableExtra)

# ------------------------------------------------------------------------
# knitr settings 
# ------------------------------------------------------------------------

knitr::opts_chunk$set(warning = F, message = F)
options(scientific=T, digits = 3) 

# ------------------------------------------------------------------------
# load plots
# ------------------------------------------------------------------------

source('gradCafeEDA.R')

```

## Introduction 

### Previous research in graduate school admissions

## Research Questions

## Exploratory Data Analysis 

### Dataset & Codebook 
```{r}
codebook.pl 
```

### Missing values and potential limitations 

```{r}
missing_data_all.pl
missing_data_acc.pl

```


## Question 2: 

## Question 3: 